### ISSUE TITLE
测试中发现book 和member 正常，record移植有些问题

### ISSUE THREAD

**Issue by xinnix** [cloud-bean/migrate#1]
好像是写入mongodb时，显示有重复键

```
 err: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: hbg.member.$card_number_1  dup key: { : "00000039" }' }
{ [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: hbg.member.$card_number_1  dup key: { : "00000048" }]
  name: 'MongoError',
  code: 11000,
  err: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: hbg.member.$card_number_1  dup key: { : "00000048" }' }
{ [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: hbg.member.$card_number_1  dup key: { : "40000020" }]
  name: 'MongoError',
  code: 11000,
```

**Comment by hygkui** [comment]
这个错误是因为在member的model中把card_number设置了唯一属性，所以如果插入重复的会提示错误。

但是应该出错在member的mig过程中啊，为什么在record的时候呢？

2015-03-16 22:32 GMT+08:00 xinnix notifications@github.com:

> 好像是写入mongodb时，显示有重复键
> ‘’‘
> err: 'insertDocument :: caused by :: 11000 E11000 duplicate key error
> index: hbg.member.$card_number_1 dup key: { : "00000039" }' }
> { [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key
> error index: hbg.member.$card_number_1 dup key: { : "00000048" }]
> name: 'MongoError',
> code: 11000,
> err: 'insertDocument :: caused by :: 11000 E11000 duplicate key error
> index: hbg.member.$card_number_1 dup key: { : "00000048" }' }
> { [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key
> error index: hbg.member.$card_number_1 dup key: { : "40000020" }]
> name: 'MongoError',
> code: 11000,
> ’‘’
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloud-bean/migrate/issues/1.

## 

人生无常
it's the life
C'est La Vie

**Comment by hygkui** [comment]
fixed, check this [diff](https://github.com/cloud-bean/migrate/commit/a44bd0bdc1c08430da42e4c2e4ad762f704563bb)
